version: '3'
services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    network_mode: host
    ports:
      - 8978:8978
    volumes:
      - /var/cloudbeaver/workspace:/opt/cloudbeaver/workspace
